import Link from "next/link";
import Image from "next/image";
import styles from "./vision.module.css";

export const metadata = {
  title: "Our Vision | Our Day Studio — Redefining the Digital Wedding Invitation",
  description: "Discover the philosophy behind Our Day Studio. We believe your wedding invitation deserves to be as meaningful and memorable as the day itself.",
};

export default function Vision() {
  return (
    <div className={styles.page}>

      {/* Hero */}
      <section className={styles.hero}>
        <div className="container">
          <span className="label animate-fade-in-up">Our Vision</span>
          <h1 className="heading-xl animate-fade-in-up delay-1">
            Your Invitation Should Be as Memorable as Your Day
          </h1>
          <p className="text-lg animate-fade-in-up delay-2" style={{ maxWidth: '650px' }}>
            We founded Our Day Studio with a simple conviction: a wedding invitation is more than logistics — it&apos;s the very first chapter of your celebration. It deserves beauty, intention, and soul.
          </p>
        </div>
      </section>

      {/* Story */}
      <section className={styles.storySection}>
        <div className="container">
          <div className={styles.storyGrid}>
            <div className={styles.storyImageWrapper}>
              <Image
                src="/images/champagne.png"
                alt="Elegant champagne wedding invitation"
                width={500}
                height={600}
                className={styles.storyImage}
              />
            </div>
            <div className={styles.storyText}>
              <span className="label" style={{ display: 'block', marginBottom: '1rem' }}>Why We Exist</span>
              <h2 className="heading-lg">Born from a Desire to Elevate</h2>
              <p className="text-lg" style={{ marginTop: '1.5rem' }}>
                Traditional paper invitations are beautiful — but they often get lost, arrive late, or lack the interactive depth that modern celebrations demand. Mass-produced digital alternatives, meanwhile, feel impersonal and disposable.
              </p>
              <p className="text-lg" style={{ marginTop: '1rem' }}>
                Our Day was born in the space between these two worlds. We combine the timeless elegance of classic stationery with the power and convenience of digital technology — creating immersive, interactive experiences that your guests will remember long after the last dance.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Values */}
      <section className={styles.valuesSection}>
        <div className="container">
          <div className="section-header">
            <span className="label">Our Values</span>
            <h2 className="heading-lg">The Principles That Guide Every Creation</h2>
          </div>
          <div className={styles.valuesGrid}>
            <div className={styles.valueCard}>
              <div className={styles.valueIcon}>✦</div>
              <h3 className="heading-sm">Elegance Above All</h3>
              <p className="text-sm" style={{ marginTop: '0.75rem' }}>
                Every visual element, every animation, every typographic choice is deliberate. We believe that true luxury lies in the details — and we obsess over each one.
              </p>
            </div>
            <div className={styles.valueCard}>
              <div className={styles.valueIcon}>🤲</div>
              <h3 className="heading-sm">Personal, Not Automated</h3>
              <p className="text-sm" style={{ marginTop: '0.75rem' }}>
                Your invitation is not generated by a template engine. It is crafted by our team, in dialogue with you. Every project is unique because every couple is unique.
              </p>
            </div>
            <div className={styles.valueCard}>
              <div className={styles.valueIcon}>🌿</div>
              <h3 className="heading-sm">Sustainable by Nature</h3>
              <p className="text-sm" style={{ marginTop: '0.75rem' }}>
                A fully digital invitation means zero paper waste, no printing, and no shipping emissions. Elegance and responsibility are not mutually exclusive — they enhance each other.
              </p>
            </div>
            <div className={styles.valueCard}>
              <div className={styles.valueIcon}>💡</div>
              <h3 className="heading-sm">Innovation with Soul</h3>
              <p className="text-sm" style={{ marginTop: '0.75rem' }}>
                We harness cutting-edge web technologies — immersive animations, interactive RSVP, real-time dashboards — but always in service of emotion, never for spectacle alone.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Difference */}
      <section className={styles.differenceSection}>
        <div className="container">
          <div className={styles.differenceInner}>
            <div className={styles.differenceText}>
              <span className="label" style={{ display: 'block', marginBottom: '1rem' }}>What Sets Us Apart</span>
              <h2 className="heading-lg">More Than a Link — An Experience</h2>
              <p className="text-lg" style={{ marginTop: '1rem' }}>
                When your guests tap that link, they don&apos;t just see information. They experience an immersive unveiling — an elegant opening animation, curated music, and a journey through every detail of your celebration. From the ceremony schedule to accommodation suggestions, from the photo gallery to the RSVP — everything unfolds with intention.
              </p>
              <p className="text-lg" style={{ marginTop: '1rem' }}>
                This is what makes a Our Day invitation different. It&apos;s not a webpage. It&apos;s a moment.
              </p>
            </div>
            <div className={styles.differenceStats}>
              <div className={styles.stat}>
                <span className={styles.statNum}>500+</span>
                <span className={styles.statLabel}>Couples Served</span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statNum}>12,000+</span>
                <span className={styles.statLabel}>Guests Invited</span>
              </div>
              <div className={styles.stat}>
                <span className={styles.statNum}>98%</span>
                <span className={styles.statLabel}>Satisfaction Rate</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Commitment */}
      <section className={styles.commitmentSection}>
        <div className="container">
          <div className="section-header">
            <span className="label">Our Commitment</span>
            <h2 className="heading-lg">The Our Day Promise</h2>
          </div>
          <div className={styles.commitGrid}>
            {[
              { title: 'Transparent Pricing', desc: 'No hidden fees, no surprises. You know exactly what you pay for and what you receive — from the very first call.' },
              { title: 'Unlimited Revisions', desc: 'We refine and adjust until you are truly delighted. There is no cap on iterations and no extra charge for changes.' },
              { title: 'Lasting Access', desc: 'Your invitation link remains active as long as you need it. Even after the wedding, it becomes a beautiful digital keepsake.' },
            ].map((item, i) => (
              <div key={i} className={styles.commitCard}>
                <h4 className="heading-sm">{item.title}</h4>
                <p className="text-sm" style={{ marginTop: '0.75rem' }}>{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className={styles.ctaSection}>
        <div className="container" style={{ textAlign: 'center' }}>
          <h2 className="heading-lg">Let&apos;s Create Something Beautiful Together</h2>
          <p className="text-lg" style={{ marginTop: '0.75rem' }}>Your story deserves an invitation worthy of it.</p>
          <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem', justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/checkout" className="btn-primary" style={{ backgroundColor: 'var(--color-background)', color: 'var(--color-foreground)', borderColor: 'var(--color-background)' }}>
              Order Now
            </Link>
            <Link href="/gallery" className="btn-secondary" style={{ borderColor: 'rgba(250,249,246,0.3)', color: 'var(--color-background)' }}>
              Explore Gallery
            </Link>
          </div>
        </div>
      </section>

    </div>
  );
}
